### ISSUE TITLE
[React Native] Download issue 

### ISSUE THREAD

**Issue by lorenc-tomasz** [Zentrust/OTPublishersHeadlessSDK#18]
Hi,
I couldn't find the place to write about this issue but after updating the React Native SDK to version higher after `202209.1.1` causes the `OneTrust download failed with error Error: Optional(OTPublishersHeadlessSDK.ManagerError.invalidDownloadData)` issue.

**Comment by lorenc-tomasz** [comment]
On native code the error response looks like: 

```
error	Error?	(error = <parent failed to evaluate: Unable to determine byte size.>)	some
```

**Comment by lorenc-tomasz** [comment]
The same on Android

**Comment by naleon** [comment]
same

**Comment by jkraus-wyn** [comment]
@lorenc-tomasz any update? getting same thing as you.

**Comment by lorenc-tomasz** [comment]
@jkraus-wyn Yes. The SDK version used in app has to be the same as in the OneTrust dashboard. Basically in OneTrust dashboard you can set the SDK version and if it matches the sdk version in the app, it works. I was not aware of this, as I had no access to OneTrust dashboard.
