### ISSUE TITLE
Privacy Manifest - Required Reason APIs

### ISSUE THREAD

**Issue by nwelchbauer-disney** [Zentrust/OTPublishersHeadlessSDK#24]
Starting Spring 2024, third-party iOS SDKs are required to include PrivacyInfo.xcprivacy manifests detailing reasons for usage of certain privacy-sensitive APIs.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

This SDK should include a PrivacyInfo.xcprivacy.

**Comment by harshbytes9026** [comment]
+1

**Comment by harshbytes9026** [comment]
To the maintainers here: The deadline is about to be missed. Can you please add PrivacyInfo.xcprivacy into the SDK?

**Comment by LFioriniReply** [comment]
Is there any news on this?

**Comment by nwelchbauer-disney** [comment]
Privacy manifest appears available since November, closing issue.
