### ISSUE TITLE
Latest SPM version is 6.34.1 even though latest version is 6.36.0

### ISSUE THREAD

**Issue by idrougge** [Zentrust/OTPublishersHeadlessSDK#9]
SDK Version 6.36 was released a week ago, yet the version published here is 6.34.1 which is over a month old and doesn’t work.

**Comment by mobileOneTrust** [comment]
@idrougge  
We have currently halted publishing latest versions of iOS OneTrust SDK via Swift Package Manager. 
Sorry for the inconvenience. We are actively looking into the issue and will resume publishing as soon as we resolve the issue.
